/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './app/routes/__root'
import { Route as LayoutImport } from './app/routes/_layout'
import { Route as Import } from './app/routes/*'
import { Route as TodosTodoIdImport } from './app/routes/todos/$todoId'
import { Route as PostsPostIdImport } from './app/routes/posts/$postId'
import { Route as LayoutLayoutBImport } from './app/routes/_layout/layout-b'
import { Route as LayoutLayoutAImport } from './app/routes/_layout/layout-a'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const TodosIndexLazyImport = createFileRoute('/todos/')()
const PostsIndexLazyImport = createFileRoute('/posts/')()
const AboutIndexLazyImport = createFileRoute('/about/')()

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const Route = Import.update({
  path: '/*',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./app/routes/index.lazy').then((d) => d.Route))

const TodosIndexLazyRoute = TodosIndexLazyImport.update({
  path: '/todos/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./app/routes/todos/index.lazy').then((d) => d.Route),
)

const PostsIndexLazyRoute = PostsIndexLazyImport.update({
  path: '/posts/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./app/routes/posts/index.lazy').then((d) => d.Route),
)

const AboutIndexLazyRoute = AboutIndexLazyImport.update({
  path: '/about/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./app/routes/about/index.lazy').then((d) => d.Route),
)

const TodosTodoIdRoute = TodosTodoIdImport.update({
  path: '/todos/$todoId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./app/routes/todos/$todoId.lazy').then((d) => d.Route),
)

const PostsPostIdRoute = PostsPostIdImport.update({
  path: '/posts/$postId',
  getParentRoute: () => rootRoute,
} as any)

const LayoutLayoutBRoute = LayoutLayoutBImport.update({
  path: '/layout-b',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutLayoutARoute = LayoutLayoutAImport.update({
  path: '/layout-a',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/*': {
      preLoaderRoute: typeof Import
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/layout-a': {
      preLoaderRoute: typeof LayoutLayoutAImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/layout-b': {
      preLoaderRoute: typeof LayoutLayoutBImport
      parentRoute: typeof LayoutImport
    }
    '/posts/$postId': {
      preLoaderRoute: typeof PostsPostIdImport
      parentRoute: typeof rootRoute
    }
    '/todos/$todoId': {
      preLoaderRoute: typeof TodosTodoIdImport
      parentRoute: typeof rootRoute
    }
    '/about/': {
      preLoaderRoute: typeof AboutIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/posts/': {
      preLoaderRoute: typeof PostsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/todos/': {
      preLoaderRoute: typeof TodosIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  Route,
  LayoutRoute.addChildren([LayoutLayoutARoute, LayoutLayoutBRoute]),
  PostsPostIdRoute,
  TodosTodoIdRoute,
  AboutIndexLazyRoute,
  PostsIndexLazyRoute,
  TodosIndexLazyRoute,
])

/* prettier-ignore-end */
